user root;
worker_processes 1;

events {
}

http {
    default_type  application/octet-stream;
    include /etc/nginx/mime.types;

    # rate limiting storage
    limit_req_zone $binary_remote_addr zone=default_limit:10m rate=5r/s;
    # by default nginx returns 503
    limit_req_status 429;

    server {
        listen 80;
        server_name partrick.todolist.backend.com;

        location /api/ {
            limit_req zone=default_limit burst=10 nodelay;

            proxy_pass http://backend:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
