# Generated by Django 6.0.1 on 2026-01-17 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('issued', 'Issued'), ('closed', 'Closed')], default='issued', max_length=10),
        ),
    ]
