# Generated by Django 6.0.1 on 2026-01-14 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, choices=[('admin', 'Admin'), ('owner', 'Owner')], max_length=10, null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='groups.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroupTask',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tasks.task')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='groups.member')),
            ],
            bases=('tasks.task',),
        ),
        migrations.CreateModel(
            name='MemberTaskRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_close', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_members', to='groups.grouptask')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_group_tasks', to='groups.member')),
            ],
        ),
        migrations.AddConstraint(
            model_name='member',
            constraint=models.UniqueConstraint(fields=('user', 'group'), name='unique_user_group'),
        ),
        migrations.AddConstraint(
            model_name='membertaskrelation',
            constraint=models.UniqueConstraint(fields=('member', 'group_task'), name='unique_member_group_task'),
        ),
    ]
